version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Europe/Berlin"
    labels:
      - "github_actions"
      - "dependencies"
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "05:00"
      timezone: "America/New_York"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 99
