
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-version: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: ./.github/workflows/test.yml
        with:
          os-version: ${{ matrix.os-version }}
          python-version: ${{ matrix.python-version }}
