
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Github editor is 127 chars wide
          flake8 . --count --exit-zero --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-version: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: ./.github/workflows/test.yml
        with:
          os-version: ${{ matrix.os-version }}
          python-version: ${{ matrix.python-version }}
