name: Labeler

on:
  push:
    paths:
      - '.github/labels.yml'
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        if: ${{ !env.ACT }}
        uses: crazy-max/ghaction-github-labeler@v5.0.0
        with:
          skip-delete: true
