on:
  workflow_dispatch:
    inputs:
      os-version:
        description: 'Value passed to "runs-on"'
        required: false
        default: ubuntu-latest
      python-version:
        description: 'Python version'
        required: false
        default: '3.10'
  workflow_call:
    inputs:
      os-version:
        description: 'Value passed to "runs-on"'
        required: true
      python-version:
        description: 'Python version'
        required: true

jobs:
  setup:
    runs-on: ${{ inputs.os-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python --version
          python -m pip install -U pip
          pip install flake8 pytest pytest-cov pytest-custom_exit_code
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install package under test
        run: |
          pip install -e .

  test:
    needs: setup
    runs-on: ${{ inputs.os-version }}
    steps:
      - name: Test with pytest
        run: |
          pytest -sv --suppress-no-test-exit-code --cov=python_package
